In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import ConfusionMatrixDisplay

In [2]:
iris=datasets.load_iris()
#iris

In [3]:
data = pd.DataFrame(np.append(iris.data,iris.target.reshape(-1,1),axis = 1),columns = ['sl','sw','pl','pw','y'])

In [4]:
data.head()

sl   sw   pl   pw    y
0  5.1  3.5  1.4  0.2  0.0
1  4.9  3.0  1.4  0.2  0.0
2  4.7  3.2  1.3  0.2  0.0
3  4.6  3.1  1.5  0.2  0.0
4  5.0  3.6  1.4  0.2  0.0

In [5]:
def label(val, *boundaries):
    if (val < boundaries[0]):       
        return 1                  
    elif (val < boundaries[1]):
        return 2
    elif (val < boundaries[2]):            ##here i have converted continuous data to discrete values of 1 ,2 ,3, 4 in each column
                                        #by <mean to be 2 , <(mean+min)/2 to be 1, <(mean+max)/2 to be 3 else to be 4                      
            return 3
    else:
        return 4


In [6]:
#Function to find label for a value
# if min_value <=val < (min_value + mean_value) / 2 ----> label a
# if (min_value + mean_value) <=val < mean_value ----> label b
# if (mean_value) <=val < (mean_value + max_value)/2 ----> label c
# if (mean_value + max_value)/2 <=val <= max_value ----> label d

def label(val, *boundaries):
    if (val < boundaries[0]):
        return 1
    elif (val < boundaries[1]):
        return 2
    elif (val < boundaries[2]):
        return 3
    else:
        return 4

#Function to convert a continuous data into labelled data
#There are 4 lables  - a, b, c, d


def toLabel(df, old_feature_name):
    second = df[old_feature_name].mean()
    minimum = df[old_feature_name].min()
    first = (minimum + second)/2
    maximum = df[old_feature_name].max()
    third = (maximum + second)/2
    return df[old_feature_name].apply(label, args= (first, second, third))

In [7]:
data['sl_labeled'] = toLabel(data, 'sl')    #relabeling columns with discrete values and their header name
data['sw_labeled'] = toLabel(data, 'sw')
data['pl_labeled'] = toLabel(data, 'pl')
data['pw_labeled'] = toLabel(data, 'pw')

In [8]:
data

sl   sw   pl   pw    y  sl_labeled  sw_labeled  pl_labeled  pw_labeled
0    5.1  3.5  1.4  0.2  0.0           2           3           1           1
1    4.9  3.0  1.4  0.2  0.0           1           2           1           1
2    4.7  3.2  1.3  0.2  0.0           1           3           1           1
3    4.6  3.1  1.5  0.2  0.0           1           3           1           1
4    5.0  3.6  1.4  0.2  0.0           1           3           1           1
..   ...  ...  ...  ...  ...         ...         ...         ...         ...
145  6.7  3.0  5.2  2.3  2.0           3           2           3           4
146  6.3  2.5  5.0  1.9  2.0           3           1           3           4
147  6.5  3.0  5.2  2.0  2.0           3           2           3           4
148  6.2  3.4  5.4  2.3  2.0           3           3           4           4
149  5.9  3.0  5.1  1.8  2.0           3           2           3           3

[150 rows x 9 columns]

In [9]:
data.drop(['sl','sw','pl','pw'],axis=1,inplace=True)

In [10]:
data.head()

y  sl_labeled  sw_labeled  pl_labeled  pw_labeled
0  0.0           2           3           1           1
1  0.0           1           2           1           1
2  0.0           1           3           1           1
3  0.0           1           3           1           1
4  0.0           1           3           1           1

In [11]:
col=['sl_labeled','sw_labeled','pl_labeled','pw_labeled','y']
data=data.reindex(columns=col)

In [12]:
data

sl_labeled  sw_labeled  pl_labeled  pw_labeled    y
0             2           3           1           1  0.0
1             1           2           1           1  0.0
2             1           3           1           1  0.0
3             1           3           1           1  0.0
4             1           3           1           1  0.0
..          ...         ...         ...         ...  ...
145           3           2           3           4  2.0
146           3           1           3           4  2.0
147           3           2           3           4  2.0
148           3           3           4           4  2.0
149           3           2           3           3  2.0

[150 rows x 5 columns]

In [13]:
set(data['sl_labeled'])

{1, 2, 3, 4}

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(data.iloc[:,0:4],data.iloc[:,4],random_state=1)
X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [15]:
clf=DecisionTreeClassifier()

In [16]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier()

In [17]:
clf.score(X_test,Y_test)

1.0

In [ ]:
#converting feature columns and outputs in numpy array
unused_features = np.array(df.columns)
#unused_features.remove('y')
xx = list(df.as_matrix(columns=unused_features))  ##numpy matrix of feature values

y = np.array(df['y'])  ##numpy matrix of output values

In [51]:
unused_features = np.array(data.columns)
unused_features=np.delete(unused_features,4,axis=0)
p


array(['sl_labeled', 'sw_labeled', 'pl_labeled', 'pw_labeled'],
      dtype=object)

In [61]:
m=data[[i for i in unused_features]]
m

sl_labeled  sw_labeled  pl_labeled  pw_labeled    y
0             2           3           1           1  0.0
1             1           2           1           1  0.0
2             1           3           1           1  0.0
3             1           3           1           1  0.0
4             1           3           1           1  0.0
..          ...         ...         ...         ...  ...
145           3           2           3           4  2.0
146           3           1           3           4  2.0
147           3           2           3           4  2.0
148           3           3           4           4  2.0
149           3           2           3           3  2.0

[150 rows x 5 columns]

In [29]:
help(pd.DataFrame.values)

Help on property:

    Return a Numpy representation of the DataFrame.
    
    .. warning::
    
       We recommend using :meth:`DataFrame.to_numpy` instead.
    
    Only the values in the DataFrame will be returned, the axes labels
    will be removed.
    
    Returns
    -------
    numpy.ndarray
        The values of the DataFrame.
    
    See Also
    --------
    DataFrame.to_numpy : Recommended alternative to this method.
    DataFrame.index : Retrieve the index labels.
    DataFrame.columns : Retrieving the column names.
    
    Notes
    -----
    The dtype will be a lower-common-denominator dtype (implicit
    upcasting); that is to say if the dtypes (even of numeric types)
    are mixed, the one that accommodates all will be chosen. Use this
    with care if you are not dealing with the blocks.
    
    e.g. If the dtypes are float16 and float32, dtype will be upcast to
    float32.  If dtypes are int32 and uint8, dtype will be upcast to
    int32. By :func:`numpy.find_

In [ ]:
c=np.asarray(b,dtype=object)

In [20]:
unused_features=np.array(data.columns)

In [21]:
unused_features.

array(['sl_labeled', 'sw_labeled', 'pl_labeled', 'pw_labeled', 'y'],
      dtype=object)

In [25]:
list(data.values) 

[array([2., 3., 1., 1., 0.]),
 array([1., 2., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 2., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 2., 1., 1., 0.]),
 array([1., 2., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 2., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([1., 3., 1., 1., 0.]),
 array([2., 3., 1., 1., 0.]),
 array([2., 4., 1., 1., 0.]),
 array([2.

numpy.ndarray

In [ ]:
## Function for calculaing the entropy for any dataset whether it may be Parent or children
import math
def calEntropy(dataSet):
    entropy=0
    labelList=[example[-1] for example in dataSet]
    uniqueLabelSet=set(labelList) ## stores a particular value only once 
    labelCount={}
    for label in labelList:
        if label not in labelCount.keys():
            labelCount[label]=0
        labelCount[label]+=1
    for label in uniqueLabelSet:
        prob=float(labelCount[label])/len(dataSet)
        entropy-=prob*math.log(prob,2)
    return entropy

In [ ]:
## It is just used for the split of dataset  according to a given feature
def splitDataSet(dataSet,feature,value):
    returnDataSet=[]
    for sample in dataSet:
        if sample[feature]==value:
            reducedSample=np.concatenate((sample[:feature],sample[feature+1:]))
            returnDataSet.append(reducedSample) #### Splitted dataset
    return returnDataSet

In [ ]:
#This function decides the best feature to split upon using information gain

def bestFeatureToSplit(dataSet):
    featureNum=len(dataSet[0])-1                # counts the total no. of features 
    
    bestFeature=-1
    bestInfoGain=0.0
    baseEntropy=calEntropy(dataSet)             # calculates entropy for each incoming dataset
    
    print('current Entropy is = %.16f' % baseEntropy)
    
    
    if baseEntropy==0:                   ## check for pure nodes
        print('Reached Leaf node')  # and declaring them terminal node(leaf) thereafter
    
    # Calculating  the informatin gain by first calculating the entropy for each children 
    # and then subtracting their weighted avg. from the parent( baseEntropy)
    
    for feature in range(featureNum):
            newEntropy=0
            featureValue=[example[feature] for example in dataSet]
            
            uniqueFeatureValue=set(featureValue) ## stores a particular value only once 
            
            for value in uniqueFeatureValue:
                subDataSet=splitDataSet(dataSet,feature,value)
                prob=float(len(subDataSet))/len(dataSet)
                newEntropy+=prob*calEntropy(subDataSet)
            
            infoGain=baseEntropy-newEntropy
            
            if infoGain>bestInfoGain:
                bestInfoGain=infoGain
                bestFeature=feature
    
    
    ## Finding the split information by calculating sort of internal entropy within the feature for each feature value 
    
    splitinfo=0
    labelList=[example[bestFeature] for example in dataSet]
    uniqueLabelSet=set(labelList)
    labelCount={}
    
    for label in labelList:
        if label not in labelCount.keys():
            labelCount[label]=0
        labelCount[label]+=1
    
    for label in uniqueLabelSet:
        prob=float(labelCount[label])/len(dataSet)
        splitinfo-=prob*math.log(prob,2)   
        
    gain_ratio=bestInfoGain/splitinfo## Finding the gain ratio
    
    
    #### Printing which feature is currently getting used for split with all the parameters calculated for the split
    print('Splitting on feature %s with gain ratio %.16f'%(unused_features[bestFeature],gain_ratio))
    print("\n")
    return bestFeature

In [ ]:
## function for calculating majority count for an impure node 

import operator
def majorityCnt(classList):
    classCount={}
    for vote in classList:
        if vote not in classCount.keys():
            classCount[vote]=0
        classCount[vote]+=1
    sortedClassCount=sorted(classCount,reverse=True)
    return sortedClassCount

## final output for an impure node = sortedClassCount

In [ ]:
def generateTree(dataSet,label,level,olddata):
    
    labelList_=[example[-1] for example in dataSet] ## label/output list for dataset 
    
    uniqueLabelSet_=set(labelList_)                 ## comprises of only uniquely identified labels 
    
    labelCount_={}                                  ## Dictionary that keeps count(value) for each label(key)
    
    
    for label_ in labelList_:
        if label_ not in labelCount_.keys():        ## starts label count for already present label as well as 
            labelCount_[label_]=0                   ## intializes count for the newly identified labels
        labelCount_[label_]+=1
        
        
   
    
    ##### Printing the level number at which evaluation takes place ####### 
    if dataSet!=olddata:
        level+=1
        olddata=dataSet
        print('Level ',level)
    else:
        print('Level ',level)
    ###### Printing Over #######
    
    
    
    ##### printing the count of labels corresponding to each parent or child in present dataset #####           
    for i in labelCount_:    
        print('Count of %s  = %d'%(i,labelCount_[i]))
        if (calEntropy(dataSet))==0:    ## Special check whether or not the leaf node reached
            print('Current Entropy is: %f'%calEntropy(dataSet))
            print('Reached leaf Node',end='\n\n')        
    ######## Printing over ###########
    
    
    
    labelList=[example[-1] for example in dataSet]    ## creates list of the labels in present dataset
    
    
    
    ###### TERMINATION CONDITIONS for Recursion #####
    if labelList.count(labelList[0])==len(labelList):  ## condition for checking if or not node is pure 
        return labelList[0] 
    
    
    if len(dataSet[0])==1:            #### If the node isn't pure then we vote for the majority labels present in the dataset 
        return majorityCnt(labelList)
    #### END of TERMINATION CONDITIONS #####
    
    
    
    bestFeature=bestFeatureToSplit(dataSet) ## calling the bestFeatureToSplit() to know the best feature to split upon
    bestFeatureLabel=label[bestFeature]
    DecisionTree={bestFeatureLabel:{}} #### Creating a nested dictionary containing our decision tree 
    
    ## For above dictionary :-
    ## keys =features on which split has taken place at each step
    ## Value=the corresponding output if the current node is a leaf otherwise another dictionary for next feature split
    
    
    del(label[bestFeature]) #### Deleting the feature upon which split has already taken place
    
    
    ##### Starting the actual decision making by using best feature split 
    
    featureValues=[example[bestFeature] for example in dataSet]
    uniqueFeatureValues=set(featureValues) ## stores a particular value only once 
    
    #print(uniqueFeatureValues)
    for value in uniqueFeatureValues:
        subDataSet=splitDataSet(dataSet,bestFeature,value)
        subLabel=label[:]
        DecisionTree[bestFeatureLabel][value]=generateTree(subDataSet,subLabel,level,olddata)##Recursion call for reduced dataset after split  
    return DecisionTree
DecisionTree=generateTree(xx,unused_features,0,xx)
print()
print('# Printing decision tree in form of nested dictionary retured by generateTree() function :',end='\n\n')
print(DecisionTree)

In [ ]:
# cook your dish here
T=int(input())
for i in range(0,T):
    X,Y=input().split()
    X=int(X)
    Y=int(Y)
    if X+Y>6:
        print("YES")
    else:
        print("NO")

2
4 5
YES


In [64]:
a='789'
a.split()

['789']

In [68]:
(a,b)=(5,9)

In [69]:
a

5